services:
  app:
    build:
      context: .
    image: top-contributors:latest
    container_name: top-contrib
    restart: unless-stopped
    environment:
      DB_URL: mongodb://mongodb:27017/top-contributors
      PORT: 8080
      HOST: localhost
    networks:
      - contributions-network
    ports:
      - "8080:8080"
  
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: top-contributors
    networks:
      - contributions-network
    ports:
      - "27017:27017"

  

networks:
  contributions-network:
    driver: bridge
